# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EBAG' do
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTActionSheet',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport',
  'RCTNetwork',
  'RCTText',
  'RCTImage',
  'RCTPushNotification',
  'RCTWebSocket',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTLinkingIOS',
  'RCTSettings',
  'RCTVibration'
  ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
  copy_pods_resources_path = "Pods/Target Support Files/Pods-EBAG/Pods-EBAG-resources.sh"
  string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
  assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
  text = File.read(copy_pods_resources_path)
  new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
  File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
end
